(deftheme Lambda
  "Created 2022-09-26.")

(custom-theme-set-faces
 'Lambda
 '(cursor ((t (:background "#c0c5ce"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#ffffff"))))
 '(highlight ((((class color) (min-colors 88) (background light)) (:background "darkseagreen2")) (((class color) (min-colors 88) (background dark)) (:background "darkolivegreen")) (((class color) (min-colors 16) (background light)) (:background "darkseagreen2")) (((class color) (min-colors 16) (background dark)) (:background "darkolivegreen")) (((class color) (min-colors 8)) (:foreground "black" :background "green")) (t (:inverse-video t))))
 '(region ((t (:background "grey20" :foreground "#ffffff"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:extend t :background "yellow1")) (((class color) (min-colors 88) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:extend t :background "yellow")) (((class color) (min-colors 16) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 8)) (:extend t :foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "#c0c5ce" :weight bold))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:foreground "#aaaaaa" :italic t))))
 '(font-lock-constant-face ((t (:foreground "#928a7e" :weight bold))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-doc-markup-face ((t (:inherit font-lock-constant-face))))
 '(font-lock-function-name-face ((t (:foreground "#ffffff" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "#ffffff" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#c0c5ce"))))
 '(font-lock-preprocessor-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:inherit bold))))
 '(font-lock-regexp-grouping-construct ((t (:inherit bold))))
 '(font-lock-string-face ((t (:foreground "#a7bca4"))))
 '(font-lock-type-face ((t (:foreground "#ffffff"))))
 '(font-lock-variable-name-face ((t (:foreground "#c0c5ce"))))
 '(font-lock-warning-face ((t (:foreground "#ffffff" :underline (:color "#ff0000" :style wave)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline t))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:background "#000000"))))
 '(header-line ((t (:inherit mode-line :background "grey20" :foreground "grey90" :box nil))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :color "#666666") :background "#222222" :foreground "#ffffff"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((supports :box t) (class color) (min-colors 88)) (:box (:line-width (2 . 2) :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width -1 :color "#666666") :background "#000000" :foreground "#666666"))))
 '(isearch ((t (:background "#aaaaaa" :foreground "#ffffff" :bold t))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:background "#666666" :foreground "#ffffff"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "khaki1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(show-paren-match ((t (:background "#000000" :foreground "#00ff00" :bold t))))
 '(show-paren-mismatch ((t (:background "#000000" :foreground "#ff0000" :bold t))))
 '(line-number ((t (:foreground "#666666"))))
 '(linum ((t (:inherit line-number))))
 '(vertical-border ((t (:foreground "#666666"))))
 '(eshell-prompt ((t (:foreground "#ffffff" :bold t))))
 '(eshell-ls-directory ((t (:foreground "#ffffff" :bold t))))
 '(eshell-ls-archive ((t (:inherit eshell-ls-unreadable))))
 '(eshell-ls-backup ((t (:inherit eshell-ls-unreadable))))
 '(eshell-ls-clutter ((t (:inherit eshell-ls-unreadable))))
 '(eshell-ls-executable ((t (:inherit eshell-ls-unreadable))))
 '(eshell-ls-missing ((t (:inherit eshell-ls-unreadable))))
 '(eshell-ls-product ((t (:inherit eshell-ls-unreadable))))
 '(eshell-ls-readonly ((t (:inherit eshell-ls-unreadable))))
 '(eshell-ls-special ((t (:inherit eshell-ls-unreadable))))
 '(eshell-ls-symlink ((t (:inherit eshell-ls-unreadable))))
 '(company-tooltip ((t (:background "#222222" :foreground "#ffffff"))))
 '(company-tooltip-selection ((t (:background "#666666" :foreground "#ffffff"))))
 '(company-tooltip-common ((t (:weight bold))))
 '(company-tooltip-common-selection ((t (:weight bold))))
 '(company-scrollbar-bg ((t (:background "#666666"))))
 '(company-scrollbar-fg ((t (:background "#aaaaaa"))))
 '(company-tooltip-annotation-selection ((t (:background "#666666" :foreground "#ffffff" :italic t))))
 '(company-tooltip-annotation ((t (:background "#222222" :foreground "#aaaaaa" :italic t))))
 '(git-gutter:modified ((t (:background "#fda50f" :foreground "#fda50f"))))
 '(git-gutter:added ((t (:background "#00ff00" :foreground "#00ff00"))))
 '(git-gutter:deleted ((t (:background "#ff0000" :foreground "#ff0000"))))
 '(diff-hl-change ((t (:background "#fda50f" :foreground "#fda50f"))))
 '(diff-hl-insert ((t (:background "#00ff00" :foreground "#00ff00"))))
 '(diff-hl-delete ((t (:background "#ff0000" :foreground "#ff0000"))))
 '(hl-line ((t (:background "#222222"))))
 '(highlight-current-line-face ((t (:inherit hl-line))))
 '(ido-first-match ((t (:weight bold))))
 '(ido-only-match ((t (:weight bold))))
 '(ido-subdir ((t (:slant italic))))
 '(ido-virtual ((t (:foreground "#aaaaaa"))))
 '(ido-vertical-match-face ((t (:slant normal :weight bold))))
 '(org-table ((t (:foreground "#aaaaaa"))))
 '(default ((t (:background "gray6" :foreground "#c0c5ce")))))

(provide-theme 'Lambda)
